"""
Django settings for e_waste_recycling project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ  # Import django-environ package to read .env variables

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables reader
env = environ.Env(DEBUG=(bool, False))  # Cast DEBUG as boolean, default is False

# Read environment configurations from .env file
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")  # Read SECRET_KEY dynamically from .env file

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)  # Read DEBUG dynamically from .env file

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # ------------- Add (App)
    "app_1_users",
    "app_2_e_Facility",
    "app_3_Recycling_info",
    "app_4_Education",
    "app_5_Home",
    "app_6_Brands",
    "app_7_Category_Brand_Mapping",
    "app_8_Reward_Rules",
    "app_9_Reward_Products",
    "app_10_E_Waste_Submission",
    "app_11_User_Rewards",
    "app_12_Reward_Cart",
    "app_13_reward_orders",
    "app_14_reward_returns",
    "app_15_reward_replaces",
    "rest_framework",  # (DRF) for building APIs
    "django_filters",  # Filtering & search functionality in DRF
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "e_waste_recycling.middleware.NormalizeDoubleSlashMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "e_waste_recycling.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "e_waste_recycling.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": env("DB_NAME"),  # Read MySQL database name dynamically from .env
        "USER": env("DB_USER"),  # Read MySQL username dynamically from .env
        "PASSWORD": env(
            "DB_PASSWORD", default=""
        ),  # Read MySQL password dynamically from .env
        "HOST": env("DB_HOST"),  # Read MySQL host dynamically from .env
        "PORT": env("DB_PORT"),  # Read MySQL port dynamically from .env
        "OPTIONS": {
            "ssl_mode": "REQUIRED",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


CORS_ALLOW_ALL_ORIGINS = True
# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:2000",
# ]


# -----------------------------------------------------------
# ---------------------- JWT (Setting) --------------------------------
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(seconds=15),  # default = 15 = seconds
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # default = 1 day
    # "REFRESH_TOKEN_LIFETIME": timedelta(seconds=20),     # default = 20 = seconds
    # "REFRESH_TOKEN_LIFETIME": timedelta(minutes=1),  # 1 minute
}


# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     ),
#     "DEFAULT_PERMISSION_CLASSES": (
#         "rest_framework.permissions.IsAuthenticated",
#     ),
# }

TIME_ZONE = "Asia/Kolkata"
USE_TZ = True


# ============== image ==============
# MEDIA_URL = "/media/"
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# MEDIA_ROOT = os.path.join(BASE_DIR, "app_4_Education", "education_images")
# MEDIA_URL = "/education_images/"

MEDIA_ROOT = BASE_DIR
MEDIA_URL = "/media/"

# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# MEDIA_URL = "/media/"
